#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	processinitrestartenable.o	\
		processblock.o			\
		processfreeze.o			\
		processsleep.o
