#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	processblock.o			\
		processfreeze.o			\
		processinitrestartenable.o	\
		processsleep.o
