#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	changediskdevice.o	\
		chkdkgeos.o		\
		dio_openclose.o		\
		dio_cts.o		\
		dio_params.o		\
		dio_stc.o		\
		dio_read.o		\
		dio_write.o		\
		dio_writev.o		\
		enterturbo.o		\
		exitturbo.o		\
		findbambit.o		\
		newdisk.o		\
		purgeturbo.o		\
		readblock.o		\
		readbuff.o		\
		setgeosdisk.o		\
		writeblock.o		\
		writebuff.o		\
		verwriteblock.o
