#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	blkalloc.o		\
		calcblksfree.o		\
		changediskdevice.o	\
		chkdkgeos.o		\
		dio_openclose.o		\
		dio_cts.o		\
		dio_params.o		\
		dio_stc.o		\
		dio_read.o		\
		dio_write.o		\
		dio_writev.o		\
		enterturbo.o		\
		exitturbo.o		\
		findbambit.o		\
		freeblock.o		\
		getblock.o		\
		getdirhead.o		\
		getptrcurdknm.o		\
		gettrse.o		\
		newdisk.o		\
		nxtblkalloc.o		\
		opendisk.o		\
		purgeturbo.o		\
		putblock.o		\
		putdirhead.o		\
		readblock.o		\
		readbuff.o		\
		setnextfree.o		\
		setgeosdisk.o		\
		setoserror.o		\
		writeblock.o		\
		writebuff.o		\
		verwriteblock.o
