#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	startmousemode.o	\
		clearmousemode.o	\
		mouseup.o		\
		mouseoff.o		\
		drawsprite.o		\
		possprite.o		\
		enablsprite.o		\
		disablsprite.o		\
		ismseinregion.o		\
		inittextprompt.o	\
		promptoff.o		\
		prompton.o		\
		getnextchar.o		\
		mouse.o
