#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	_scrsize.o	\
		cclear.o	\
		cgetc.o		\
		chline.o	\
		clrscr.o	\
		color.o		\
		cpputs.o	\
		cputc.o		\
		cursor.o	\
		cvline.o	\
		gotoxy.o	\
		kbhit.o		\
		revers.o	\
		where.o
