#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	blkalloc.o		\
		calcblksfree.o		\
		freeblock.o		\
		getblock.o		\
		getdirhead.o		\
		getptrcurdknm.o		\
		gettrse.o		\
		nxtblkalloc.o		\
		opendisk.o		\
		putblock.o		\
		putdirhead.o		\
		setnextfree.o