#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	appendrecord.o		\
		closerecordfile.o	\
		deletefile.o		\
		deleterecord.o		\
		findfile.o		\
		findftypes.o		\
		freefile.o		\
		get1stdirentry.o	\
		getfhdrinfo.o		\
		getfile.o		\
		getnxtdirentry.o	\
		insertrecord.o		\
		nextrecord.o		\
		openrecordfile.o	\
		pointrecord.o		\
		previousrecord.o	\
		readbyte.o		\
		readfile.o		\
		readrecord.o		\
		renamefile.o		\
		savefile.o		\
		sysremove.o		\
		sysrename.o		\
		updaterecordfile.o	\
		writerecord.o