#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	bitmapclip.o		\
		bitmapregs.o		\
		bitmapup.o		\
		bitotherclip.o		\
		drawline.o		\
		drawpoint.o		\
		framerectangle.o	\
		getcharwidth.o		\
		getintcharint.o		\
		graphicsstring.o	\
		hlineregs.o		\
		horizontalline.o	\
		imprintrectangle.o	\
		initdrawwindow.o	\
		invertline.o		\
		invertrectangle.o	\
		loadcharset.o		\
		pointregs.o		\
		put_char.o		\
		putdecimal.o		\
		putstring.o		\
		recoverline.o		\
		recoverrectangle.o	\
		rectangle.o		\
		setpattern.o		\
		testpoint.o		\
		usesystemfont.o		\
		verticalline.o		\
