#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

C_OBJS +=	messagebox.o

S_OBJS +=	dbget2lines.o		\
		dlgboxgetstring.o	\
		dlgboxfileselect.o	\
		dlgboxok.o		\
		dlgboxokcancel.o	\
		dlgboxyesno.o		\
		dodlgbox.o		\
		rstrfrmdialogue.o
