#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	fio_module.o	\
		joy_stddrv.o	\
		mcbdefault.o	\
		mouse_stddrv.o	\
		tgi_colors.o	\
		tgi_stddrv.o
