#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	crt0.o		\
		extzp.o		\
		fio_module.o	\
		joy_stddrv.o	\
		mainargs.o	\
		mcbdefault.o	\
		mouse_stddrv.o	\
		oserror.o	\
		oserrlist.o	\
		randomize.o	\
		tgi_colors.o	\
		tgi_stddrv.o
