#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	domenu.o		\
		dopreviousmenu.o	\
		redomenu.o		\
		recovermenu.o		\
		recoverallmenus.o	\
		gotofirstmenu.o		\
		doicons.o
