#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	fetchram.o	\
		reuregs.o	\
		stashram.o	\
		swapram.o	\
		verifyram.o
