#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	reuregs.o	\
		stashram.o	\
		fetchram.o	\
		swapram.o	\
		verifyram.o
