#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

C_OBJS	+=	systime.o

S_OBJS  +=      ctype.o			\
		callroutine.o		\
		enterdesktop.o		\
		firstinit.o		\
		get_ostype.o		\
		getrandom.o		\
		getserialnumber.o	\
		initdoneio.o		\
		mainloop.o		\
		panic.o			\
		tobasic.o		\
		setdevice.o		\
		sysuname.o
