#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS  +=      ctype.o			\
		get_ostype.o		\
		initdoneio.o		\
		setdevice.o		\
		tobasic.o
