; Atari 7800 MARIA read / write registers
;

; Read registers
BKGRND := $00
P0C1   := $01
P0C2   := $02
P0C3   := $03
MWSYNC := $04
P1C1   := $05
P1C2   := $06
P1C3   := $07
MSTAT  := $08
P2C1   := $09
P2C2   := $0A
P2C3   := $0B
DPPH   := $0C
P3C1   := $0D
P3C2   := $0E
P3C3   := $0F
DPPL   := $10
P4C1   := $11
P4C2   := $12
P4C3   := $13
CHBASE := $14
P5C1   := $15
P5C2   := $16
P5C3   := $17
OFFSET := $18
P6C1   := $19
P6C2   := $1A
P6C3   := $1B
CTRL   := $1C
P7C1   := $1D
P7C2   := $1E
P7C3   := $1F

; Write registers

