; Atari 7800 MARIA read / write registers
;

; Read registers
BKGRND := $20
P0C1   := $21
P0C2   := $22
P0C3   := $23
MWSYNC := $24
P1C1   := $25
P1C2   := $26
P1C3   := $27
MSTAT  := $28
P2C1   := $29
P2C2   := $2A
P2C3   := $2B
DPPH   := $2C
P3C1   := $2D
P3C2   := $2E
P3C3   := $2F
DPPL   := $30
P4C1   := $31
P4C2   := $32
P4C3   := $33
CHBASE := $34
P5C1   := $35
P5C2   := $36
P5C3   := $37
OFFSET := $38
P6C1   := $39
P6C2   := $3A
P6C3   := $3B
CTRL   := $3C
P7C1   := $3D
P7C2   := $3E
P7C3   := $3F

; Write registers

