;
; PET generic definitions.
;


; ---------------------------------------------------------------------------
; Zero page, Commodore stuff

DEVNUM 	       	:= $D4 	    	; Device number



; ---------------------------------------------------------------------------
; I/O: 6522 VIA2

VIA   	       	:= $E840
VIA_PRB         := $E840
VIA_PRA         := $E841
VIA_DDRB      	:= $E842
VIA_DDRA      	:= $E843


