../tgi/nes-64-56-2.tgi: ../wrk/nes/clrscr.o \
                        ../wrk/nes/cputc.o  \
                        ../wrk/nes/get_tv.o \
                        ../wrk/nes/gotoxy.o \
                        ../wrk/nes/popa.o   \
                        ../wrk/nes/ppu.o    \
                        ../wrk/nes/ppubuf.o \
                        ../wrk/nes/setcursor.o
