#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	crc.o		\
		doublepop.o	\
		clearram.o	\
		fillram.o	\
		initram.o	\
		movedata.o	\
		doublespop.o	\
		copystring.o	\
		cmpstring.o	\
		copyfstring.o	\
		cmpfstring.o
