#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

S_OBJS +=	doicons.o		\
		domenu.o		\
		dopreviousmenu.o	\
		gotofirstmenu.o		\
		recoverallmenus.o	\
		recovermenu.o		\
		redomenu.o
