#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

C_OBJS	+=	systime.o

S_OBJS  +=      callroutine.o		\
		crt0.o			\
		enterdesktop.o		\
		extzp.o			\
		firstinit.o		\
		getrandom.o		\
		getserialnumber.o	\
		mainargs.o		\
		mainloop.o		\
		oserror.o		\
		oserrlist.o		\
		panic.o			\
		randomize.o		\
		setoserror.o		\
		sysuname.o
