#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

C_OBJS	+=	systime.o

S_OBJS  +=      callroutine.o		\
		enterdesktop.o		\
		firstinit.o		\
		getrandom.o		\
		getserialnumber.o	\
		mainloop.o		\
		panic.o			\
		sysuname.o
