#
# makefile for CC65 runtime library
#

#--------------------------------------------------------------------------
# Object files

C_OBJS +=	_afailed.o	\
		_poserror.o	\
		abort.o		\
		perror.o	\
		sleep.o

S_OBJS +=	copydata.o	\
		memcpy.o	\
		memmove.o	\
		memset.o	\
		zerobss.o
